### ISSUE TITLE
Create Product Categories assigned wrong taxonomy ID

### ISSUE THREAD

**Issue by Twilight-Computer** [givanz/Vvveb#101]
If you create a Product Category via the Ecommerce > Products > Category > Add Item, the taxonomy_id is assigned as "1" (Category -Post) instead of "4" (Category - Product).

Work around is to update the taxonomy_item table in SQL

**Comment by givanz** [comment]
I'm unable to reproduce this bug, can you please check if the request includes `taxonomy_id` like in the attached screenshot?

I added fallback code to get taxonomy_id from the page get parameters if it's missing in the post request https://github.com/givanz/Vvveb/commit/6b5d30b3ba953b6c5433c7ef56a0ece25cec5543.

![categories](https://github.com/givanz/Vvveb/assets/302738/6e698311-072d-46dd-a5b3-3c2c00dc486f)
