### ISSUE TITLE
Product Attributes - only one Attribute from each Group is displayed

### ISSUE THREAD

**Issue by Twilight-Computer** [givanz/Vvveb#103]
If a product has multiple attributes against a single group assigned to it, only the last one is displayed in the live web page.

Similarly, if attributes from multiple groups are assigned, only one from each group is displayed.

EG Product 18 in sample data has 12 attributes across three groups assigned, but only three (one from each group) is displayed in the live view of Specifications

**Comment by givanz** [comment]
Thanks for the bug report, it's fixed in the latest update.

https://github.com/givanz/Vvveb/commit/79aba6c7c732fd5b15deb74644d2be8e5ea08956
