### ISSUE TITLE
Delete from Cart add one product on

### ISSUE THREAD

**Issue by Twilight-Computer** [givanz/Vvveb#106]
If you have an item and select "X" to remove from cart, you get a message saying the item is removed, but the quantity **increases** by one

![image](https://github.com/givanz/Vvveb/assets/162770195/c29b4ea6-40e5-4d97-b6cf-5dd0907b815d)

**Comment by Twilight-Computer** [comment]
Same with main cart window:
![image](https://github.com/givanz/Vvveb/assets/162770195/9914d514-d3b0-4d48-a750-b484802e8528)

**Comment by givanz** [comment]
Thanks for the bug report, it's fixed in the latest update https://github.com/givanz/Vvveb/commit/f4bfaf42f647bdf14592c172e8d56ba455448dee

**Comment by Twilight-Computer** [comment]
Working correctly against first image (Click X from cart icon) but clicking delete icon in second image (actual cart view) does not delete the item.

**Comment by givanz** [comment]
After a few tries I managed to have delete not do anything by switching back and forth from https://www.twilightcomputer.com.au/ to https://twilightcomputer.com.au/ and adding and deleting products from cart.

I think it's related to something getting stuck with multiple sessions id cookie.

Please edit `/env.php` and enable shared session to have the same session on all subdomains

```php
defined('V_SHARED_SESSION') || define('V_SHARED_SESSION', true);
```

You will need to clear browser cookies for domain to reset sesssion.
