### ISSUE TITLE
Filter by Brand not working 

### ISSUE THREAD

**Issue by Twilight-Computer** [givanz/Vvveb#107]
I am not sure if this filter is enabled.
On the Shop page - selecting any "Brand" does not filter the results.
![image](https://github.com/givanz/Vvveb/assets/162770195/ca4d04c2-cd97-4dda-9040-d3585faccb27)

**Comment by givanz** [comment]
Filters component is missing only the html in theme is added, I will add it in the next commit.

**Comment by givanz** [comment]
Filter by brand is working with the latest commit https://github.com/givanz/Vvveb/commit/f589b8f4af67432fa6d0f41eb22006a50c6e1b81 https://github.com/givanz/landing/commit/40ba1e3d8933cccef65ada0b1b0bbfe754afd48f

**Comment by Twilight-Computer** [comment]
I have applied this, but still not seeing filter by Brand working. When filter is selected, the result in the browser shows - https://www.twilightcomputer.com.au/shop/desktops?filter[manufacturer_id][]=6 - seems like a strange character at the end of the string.?
Result shows all entries in the Category.

**Comment by givanz** [comment]
Can you please redownload `latest.zip` and override `app/components`,  `admin/sql` and `system` folders if possible overwrite all files except `config` and `public/themes` and clear cache? make sure that `storage/model/app` folder has write permission and is emptied on clear cache. 

The strange characters are `[` and `]` that are urlencoded by the browser and transformed to `%5B` and `%5D`.

**Comment by Twilight-Computer** [comment]
I have replaced all files except config and public/themes (and public/media). Cleared cache, restarted httpd and php-fpm.
Folder storage/model/app has  777 permissions. However on clearing cache, the contents of this folder is not deleted. Is this what you meant by "make sure that storage/model/app folder has write permission and is emptied on clear cache." ?
I have manually deleted the contents, and it gets rebuilt on use of the Website unfortunately still not showing filtered results.

**Comment by Twilight-Computer** [comment]
Not that I am seeing this entry multiple times in the log, but the actual file does not exist ?
PHP Deprecated:  ucfirst(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/twilight/storage/compiled-templates/admin_1_default_product_product.html on line 2022

**Comment by givanz** [comment]
> the contents of this folder is not deleted

If files are not deleted it fails silently, I added some warnings in `tools > cache` for cache folders that are not writable.

Do you use the code from github or latest.zip? Not all latest changes are on github to allow some testing before push, please update the code from latest.zip

Also `public/js/filter.js` is not the latest version with ajax support as it refreshes the page on filter change.

**Comment by givanz** [comment]
> Not that I am seeing this entry multiple times in the log, but the actual file does not exist ?

Thanks for the bug report, It's fixed in the latest update, changed file `/system/functions.php`
