### ISSUE TITLE
Is there a way to export the site as static pages?

### ISSUE THREAD

**Issue by nwkyz** [givanz/Vvveb#108]
The site works well on localhost, but is there a method to export them as a static site, or some ways to host it on cloudflare pages and github pages?
Thanks.

**Comment by givanz** [comment]
Currently there is no static export option, it will be added as a plugin in the future.
You can export manually using 

```bash
wget -r --mirror -p --convert-links -P --follow-tags=a ./  https://website.com
```

**Comment by nwkyz** [comment]
Okay thanks.
