### ISSUE TITLE
Scrolling product pages on mobile devices brings header down the page

### ISSUE THREAD

**Issue by Twilight-Computer** [givanz/Vvveb#109]
Only on the mobile layout - on desktop this is fine.

Scrolling the description of any product (sample data or newly uploaded products) - when you get the the header of the "Description / Specifications etc" it does not scroll past but moves down the page obscuring the text when reading. Image below from Product 19 example:
![24-03-31 10-34-43 1087](https://github.com/givanz/Vvveb/assets/162770195/a0700eac-e42c-4bd9-b02a-fc0d5514cfa9)

**Comment by givanz** [comment]
Thanks for the bug report, it's fixed in the latest update https://github.com/givanz/landing/commit/4ce1400a5bf141ba0e480ce576be2db3a31c6787

**Comment by Twilight-Computer** [comment]
Thank you - this has been applied and is working.
