### ISSUE TITLE
Menus on all links off index.html show same error

### ISSUE THREAD

**Issue by Twilight-Computer** [givanz/Vvveb#122]
Since a few days now, all pages linked off index.htm (eg About / Services etc) all show:

Warning: Undefined variable $generate_menu in /var/www/html/twilight/storage/compiled-templates/app_1_landing_about.html on line 233

I have checked permissions on the the storage folder and even deleted all files, but the same error occurs - suggestions ?

**Comment by givanz** [comment]
Can you please provide more details.

This is showing after page cache refresh or only when logged in the admin area? 

I checked about/services page on your site and the error is gone.

**Comment by Twilight-Computer** [comment]
Seeing all the time. Just went to website on mobile ( not logged in) and see the error? References About page. See screen shot.
 
   
     Regards ( from my iPhone)
   
   Gary Young | J.P. QBE | Twilight Computer Services
   P: +61 2 4022 9775 | M: +61 408 215 099
   PO Box 4181, Bradbury NSW 2560
   
   ***@***.*** |  www.twilightcomputer.com.au
   
   
   
   **** IMPORTANT INFORMATION *****
   This document should be read only by those persons to whom it is addressed and its content is not intended for use by any other persons. If you have received this message in error, please notify us immediately. Please also destroy and delete the message from your computer. Any unauthorised form of reproduction of this message is strictly prohibited. Twilight Computer Services is not liable for the proper and complete transmission of the information contained in this communication, nor for any delay in its receipt.
       On 29 Apr 2024, at 08:59, Givan ***@***.***> wrote:
   
   
       ﻿ Can you please provide more details. This is showing after page cache refresh or only when logged in the admin area? I checked about/services page on your site and the error is gone. —

**Comment by givanz** [comment]
I see the error now.

This is caused by a missing submenu element in the first menu item and it seems to be caused by a bug in the menu component on page save. 

To fix it please restore '/public/themes/landing/blank.html' and clear cache.

I will try to reproduce the missing submenu element on page save.

Thanks for the bug report.

**Comment by Twilight-Computer** [comment]
I restored the blank.html  file and it fixed the immediate error.

However I noted that the Google Map reference changed back to Bucharest on 
the Contact page.

Editing and saving this google reference, then (re) introduced the error 
on contact.html ?

Warning: Undefined variable $generate_menu 
in /var/www/html/twilight/storage/compiled-templates/app_1_landing_contact.html on 
line 229 

Regards, 

Gary Young J.P. QBE  
Twilight Computer Services
M: 0408 215 099  
PO Box 4181, Bradbury NSW 2560
***@***.***  |  www.twilightcomputer.com.au
Master Security License - 000100683






From:   "Givan" ***@***.***>
To:     "givanz/Vvveb" ***@***.***>
Cc:     "Twilight Computer Services" ***@***.***>, 
"Author" ***@***.***>
Date:   29/04/2024 11:40 AM
Subject:        Re: [givanz/Vvveb] Menus on all links off index.html show 
same error (Issue #122)



I see the error now.
This is caused by a missing submenu element in the first menu item and it 
seems to be caused by a bug in the menu component on page save.
To fix it please restore /public/themes/landing/blank.html and clear 
cache.
I will try to reproduce the missing submenu element on page save.
Thanks for the bug report.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by givanz** [comment]
The menu from all pages except homepage are linked using `data-v-save-global` attribute, the menu content is loaded and saved to `blank.html` on any menu change.

I'm unable to reproduce this bug,  it is caused by missing submenu on the first menu when saving but I'm unable to make it break to find the cause.

This might be an old bug or something specific to your setup.

If it still doesn't work after update you can provide me temporary access and I can investigate the cause.
