### ISSUE TITLE
Multiple products added to a Category, but only one shows in when filtering products by category

### ISSUE THREAD

**Issue by Twilight-Computer** [givanz/Vvveb#123]
I have added an number of products and selected the correct categories for them

When viewing the products page and selecting the Category filter, only one product shows 

Eg Products / filter on Monitors - only one shows.

**Comment by givanz** [comment]
Can you please update all files except `config` and `public/themes/` to rule out an old bug?

I can't reproduce this bug on my demo https://demo.vvveb.com/shop/computers
