### ISSUE TITLE
Fresh install of Latest - errors shown on startup against existing db

### ISSUE THREAD

**Issue by Twilight-Computer** [givanz/Vvveb#133]
I have opted to try a fresh install against my DB.

These lines of error appear on opening the home page:

[13-Jun-2024 14:19:42 Australia/Sydney] PHP Deprecated: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/html/testtwilight/system/core/startup.php on line 219
[13-Jun-2024 14:19:47 Australia/Sydney] PHP Warning: Undefined array key 1139 in /var/www/html/testtwilight/system/core/startup.php on line 219
[13-Jun-2024 14:19:47 Australia/Sydney] PHP Deprecated: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/html/testtwilight/system/core/startup.php on line 219
[13-Jun-2024 13:46:45 Australia/Sydney] PHP Warning: Undefined property: Vvveb\Controller\User\Wishlist::$session in /var/www/html/testtwilight/app/controller/base.php on line 267

**Comment by givanz** [comment]
Thanks for the bug reports, I fixed the php notices https://github.com/givanz/Vvveb/commit/1a2ad53dc720d141bc0fdc67cf897fec751ca418  https://github.com/givanz/Vvveb/commit/11f3b4aa378d2cd259dbd616787b3b498f1c720b

**Comment by Twilight-Computer** [comment]
FYI - I received this today and wanted to bring it to your attention.

It apparently relates to this file :

../public/medial/posts/4.jpg

I will delete the file from my server.

Regards, 

Gary Young | J.P. QBE  |  Twilight Computer Services
P: +61 2 4022 9775  |  M: +61 408 215 099 
PO Box 4181, Bradbury NSW 2560 

***@***.***   |   www.twilightcomputer.com.au 



MASTER SECURITY LICENSE 000108273

**** IMPORTANT INFORMATION *****
This document should be read only by those persons to whom it is addressed 
and its content is not intended for use by any other persons. If you have 
received this message in error, please notify us immediately. Please also 
destroy and delete the message from your computer. Any unauthorised form 
of reproduction of this message is strictly prohibited. Twilight Computer 
Services is not liable for the proper and complete transmission of the 
information contained in this communication, nor for any delay in its 
receipt. 
----- Forwarded by Twilight Computer/GSY on 14/08/2025 03:38 PM -----

From:   "Anna Brown | Citi Legal Services" ***@***.***>
To:     ***@***.***
Date:   14/08/2025 05:26 AM
Subject:        DMCA Copyright Infringement Notice



Dear owner of 
***@***.***_16;50;11.html,

We recently came across an image being used on your website and would 
like to request proper attribution. The details are as follows:

Image Details: https://i.imgur.com/UKUbJVc.png
Location of Usage: 
***@***.***_16;50;11.html

To comply with proper usage, we kindly ask that you include a visible 
credit link to our client 
https://www.cheapsurfgear.com/blogs/surf-news/mattress-pump-for-paddle-board 

near the image or in the footer of your page, using the anchor text Cheap 
Surf Gear - Paddle Board.

Please make this adjustment within the next five business days. If no 
action is taken within this period, we will refer to Case No. 57811 and 
follow up accordingly under DMCA Section 512(c).

For historical reference, past versions of the page can be reviewed 
via the Wayback Machine: https://web.archive.org.

Thank you for your time and cooperation. If you have any questions, 
feel free to reach out.

Regards

Anna Brown
Trademark Attorney 

Citi Legal Services
1 Beacon St 12th floor
Boston, MA 02108

***@***.***
www.clexpertsgroup.pro

**Comment by givanz** [comment]
This is a scam attempt, the image is from unsplash and is free to use https://unsplash.com/photos/aerial-photo-of-person-riding-boat-during-daytime-QXpDBgiH_Oo
