### ISSUE TITLE
Search does not return any product results

### ISSUE THREAD

**Issue by Twilight-Computer** [givanz/Vvveb#148]
The search icon, does not return any results for products in the database.

**Comment by givanz** [comment]
It doesn't work with some specific queries or does not work at all?

Search is using the database full text search engine that works only with words and phrases, if you want search to work for any string you can replace 

```html
data-v-search="url" 
```
with 
```
data-v-like="url" 
```

in theme `search/index.html` template

https://github.com/givanz/landing/blob/main/search/index.html#L776-L777

Like parameter was added to products and posts components in the last update, you need to update `app/component/products.php` and `app/component/posts.php`.
