### ISSUE TITLE
Failed to delete redis database cache.

### ISSUE THREAD

**Issue by Shofiul-Alam** [givanz/Vvveb#155]
I used redis docker for my stack. After, changed to cache to redis driver I had to update delete method in system/cache/redis.php driver as follow - 

```
public function delete($namespace, $key) {
        if($key){
            $this->redis->del($this->options['prefix'] . $key);
        }else{
            $keys = $this->redis->keys('*');
            $this->redis->del($keys);
        }
        return true;
	}
```

Please take a look and if this changes are ok update the framework code.

**Comment by givanz** [comment]
Thank you for delete suggestion, I included delete all keys in the last commit https://github.com/givanz/Vvveb/commit/fc9138ff7773fe244a6ad084122ee5ecb8becf6c

**Comment by Shofiul-Alam** [comment]
@givanz 
You are amazing. Many thanks.
