### ISSUE TITLE
On opening Editor right side panel show JS error

### ISSUE THREAD

**Issue by Shofiul-Alam** [givanz/Vvveb#156]
When clicking save as to save current template with a different name following error is coming up. 

<img width="1783" alt="image" src="https://github.com/givanz/Vvveb/assets/13927209/54f4be67-b60e-4ec8-9040-f590e67ec586">

Also I did not found any element input[data-v-filename]. I changed as follows in the builder.js file and it worked. Please do a review.

<img width="1128" alt="image" src="https://github.com/givanz/Vvveb/assets/13927209/85e2969f-bc3e-4c68-bc85-fc42cff2db05">

		document.querySelector("#save-offcanvas [data-v-filename]").innerHTML = filename;
		// document.querySelector("#save-offcanvas input[data-v-filename]").val(filename);
		document.querySelector("#save-offcanvas input[data-v-basename]").value = filename;
		document.querySelector("#save-offcanvas [data-v-theme-folders]").value = folder;

**Comment by givanz** [comment]
Thank you for the bug report, it's fixed in the last commit https://github.com/givanz/Vvveb/commit/fa2d148b920fcc02e25b3387de1da60cb466facb

**Comment by Shofiul-Alam** [comment]
@givanz Many many thanks.
