### ISSUE TITLE
Editor -> builder clicking on save or Save As button keep loader spinning

### ISSUE THREAD

**Issue by Shofiul-Alam** [givanz/Vvveb#157]
I found issue in builder.js file line number 2475 to 2481. It was causing spinner keep spinning after saveAjax request. Had to change code as follows. Please do a review and update.

<img width="1348" alt="image" src="https://github.com/givanz/Vvveb/assets/13927209/5f1b2cbc-6223-4950-91ed-e1385c918490">

`	btn.querySelector(".loading").classList.toggle("d-none");
			btn.querySelector(".button-text").classList.toggle("d-none");
		}, (error) => {
			btn.querySelector(".loading").classList.toggle("d-none");
			btn.querySelector(".button-text").classList.toggle("d-none");
			let message = error?.statusText ?? "Error saving!";
			displayToast("bg-danger", "Error", message);`

**Comment by givanz** [comment]
Thank you for the bug report, it's fixed in the last commit https://github.com/givanz/Vvveb/commit/fa2d148b920fcc02e25b3387de1da60cb466facb
