### ISSUE TITLE
Admin Login Page Bug

### ISSUE THREAD

**Issue by Shofiul-Alam** [givanz/Vvveb#158]
![image](https://github.com/user-attachments/assets/3770cd02-b504-4302-a38c-3386ea98e7ef)
On click Eye icon get this error.

**Comment by givanz** [comment]
Thanks for the bug report, it's fixed in the last commit https://github.com/givanz/Vvveb/commit/f49f66995d8a4a54b9cb2b781b9f51506a88dab3

**Comment by Shofiul-Alam** [comment]
Thank you so much.
