### ISSUE TITLE
Redis Cache Issue

### ISSUE THREAD

**Issue by Shofiul-Alam** [givanz/Vvveb#159]
![image](https://github.com/user-attachments/assets/81fea4ea-6c65-4c2a-8ba9-89d44629a9db)

Need to change 
$this->get($this->key($namespace, $key));

To 
$this->get($namespace, $key);

Also I found the bug after the fix $key is sending as an array but the key() method is expecting string as the key. Need change redis.php line 82 to 			
$this->set($namespace, $key, $value, $expire);

![image](https://github.com/user-attachments/assets/f5c50922-04a5-48e8-b730-1b66c690ed03)

![image](https://github.com/user-attachments/assets/6eb3eade-884e-44d9-84d4-2382d937672c)

**Comment by givanz** [comment]
Thanks for the bug report, it's fixed in the last commit https://github.com/givanz/Vvveb/commit/3e9572ba303eb2a964baffd3610fe591dd7e2571

**Comment by Shofiul-Alam** [comment]
Thanks.
