### ISSUE TITLE
Admin -> Cron page error

### ISSUE THREAD

**Issue by Shofiul-Alam** [givanz/Vvveb#161]
I found the following page error in cron page. 
<img width="1792" alt="image" src="https://github.com/user-attachments/assets/a33d94a6-3059-4381-a6b4-aaa23c2d3b4c">

Following correction requested

![image](https://github.com/user-attachments/assets/dfd2f5d7-b85e-4e8b-bd7b-03c776e1f92e)

**Comment by givanz** [comment]
Thanks for the bug report, it's fixed in the last commit https://github.com/givanz/Vvveb/issues/161

**Comment by Shofiul-Alam** [comment]
Thank you so much.
