### ISSUE TITLE
Menu not showing on live site in same order as Menu Listing

### ISSUE THREAD

**Issue by Twilight-Computer** [givanz/Vvveb#186]
I have added a new Child Menu in the Taxonomy > Menu page, but the order shown there does not match the Live Web site display.

Edited Sort Order in SQL to fix the issue, but "sorting" in the Menu Page does not seem to stick.

![image](https://github.com/user-attachments/assets/22a7d00d-5544-46d2-9139-4dc0231c8cf0)

**Comment by givanz** [comment]
Currently reordering menu items require clear cache.

I tried reordering with both existing sub items and new ones and they display in the proper order after clear cache.

If it doesn't work after clear cache please provide more details on how to reproduce the bug.
