### ISSUE TITLE
Menu Item link issue: the value of href always shows "localhost:8081"

### ISSUE THREAD

**Issue by Vander-Bilt** [givanz/Vvveb#218]
Just added one menu item,

![image](https://github.com/user-attachments/assets/c02281eb-7b14-4b83-a643-ba0e4178d7c9)

It shows up on page:
![image](https://github.com/user-attachments/assets/5b5e6824-3669-437f-899d-1e96a1d275c1)

But the href shows "localhost:8081", not "https://douyin.dx".

I tried to modify below files, but no luck, the issue exists the same.

_/admin/template/menu.tpl
/admin/template/content/menus/menu.tpl_

I am new for vvveb, did I miss something? 

Thanks for your comments.

**Comment by givanz** [comment]
Thanks for the bug report, this happens only on localhost, to fix it please redownload `latest.zip` and update `vvveb/system/sites.php`

**Comment by Vander-Bilt** [comment]
Done. Thank you so much!
