### ISSUE TITLE
Not Found issue: added simple Post or Page, got error when view/edit

### ISSUE THREAD

**Issue by Vander-Bilt** [givanz/Vvveb#220]
Just added a simple Post, tried to view, got error:

![image](https://github.com/user-attachments/assets/13df6be9-a5a6-48ff-b55f-7b9e84aa1c78)

Tried to edit, got error:
![image](https://github.com/user-attachments/assets/d0466f52-2814-4ad0-a06b-5ebc3c355883)

The same error shows up when trying to add a Page.

I am a beginner for Vvveb and don't know where I might be wrong. Please give me your guidance.

**Comment by givanz** [comment]
I checked again on localhost and the previous fix was not complete, some urls were still wrongly generated.

Please redownload `latest.zip` and update `vvveb/system/sites.php` you might need to clear cache after update.

If it still doesn't work please paste the url of the page, you can get the url by opening the page from the button in the screenshot
![editor-page-url](https://github.com/user-attachments/assets/c1b945a1-abe8-4ccc-9a8a-1595e42bf312)

**Comment by Vander-Bilt** [comment]
Thanks givanz for your reply.
I don't know how to update `vvveb/system/sites.php` to fix it.

The url of the page: 
http://myfree.com:8081/testing-post-2
http://myfree.com:8081/mypage-3

myfree.com is my local domain, in my /etc/hosts:
_127.0.0.1	myfree.com_

**Comment by givanz** [comment]
If you open the pages http://myfree.com:8081/mypage-3 and http://myfree.com:8081/testing-post-2 directly it shows the same not found error or this happes only in the page builder?

The error shows only for newly created pages or is the same for existing demo sample pages also?

Are all pages except admin and homepage loading?

To update you need to redownload `latest.zip` and copy the file to your server to Vvveb `/system` folder.

**Comment by Vander-Bilt** [comment]
After a totally new installation, 

**Admin editor:**

the error shows for existing demo sample pages Pricing, Portfolio, About...
http://myfree.com/page/pricing-13?theme=landing&r=0.25333877069997346
http://myfree.com/page/about-11?theme=landing&r=0.5154860710486813
http://myfree.com/page/portfolio-14?theme=landing&r=0.9781564394091773
http://myfree.com/page/services-12?theme=landing&r=0.7675960577778094

![image](https://github.com/user-attachments/assets/629e5b6e-21bb-4518-820d-f24998d7789e)

But for demo page Category, Shop, Product... no error.

http://myfree.com/themes/landing/product/category.html?r=0.7648372129233216
http://myfree.com/themes/landing/product/product.html?r=0.1762965211337577

![image](https://github.com/user-attachments/assets/a03c2b3e-a9f8-43a0-9b3c-6d59dadc6510)

View:

http://myfree.com/page/pricing-13
http://myfree.com/page/services-12

![image](https://github.com/user-attachments/assets/2cc48ac7-224b-4be7-b483-5dea3d44c1e2)
![image](https://github.com/user-attachments/assets/31ff349a-8abc-4543-8438-d357b8802d3d)


Product Editor:

http://myfree.com/vadmin-heidg7zj//index.php?module=product/product&product_id=19&type=product

![image](https://github.com/user-attachments/assets/7d923815-304b-4985-a64d-9f1f541fe2a9)


Product View:

http://myfree.com/product/product-eighteen-18

![image](https://github.com/user-attachments/assets/b16c4eb9-7b11-471d-96e1-1fa9f3048183)

**Comment by givanz** [comment]
Thanks for the screenshots.

The 404 not found error is generated by apache.

Some possible causes can be missing mod rewrite module or .htaccess not loaded.

To enable mod rewrite please run

```bash
sudo a2enmod rewrite
```

If it still doesn't work edit `/etc/apache2/apache2.conf` and change 

```apache
AllowOverride None
```

to 

```apache
AllowOverride All
```

to enable .htacess processing and restart apache

```bash
sudo systemctl restart apache2
```

**Comment by Vander-Bilt** [comment]
Thanks @givanz 
I checked my apache2 configuration file `/usr/local/etc/httpd/httpd.conf`, it seems like there is no issues.

![image](https://github.com/user-attachments/assets/518a7605-9203-4660-9ca8-def7741dcaef)

Attached httpd.conf: 
[httpd.conf.zip](https://github.com/user-attachments/files/17761842/httpd.conf.zip)
