### ISSUE TITLE
Admin User: The list of Roles is not including more than 10 items

### ISSUE THREAD

**Issue by m-bakoulis** [givanz/Vvveb#223]
Hi, I created a new Role and I was not able to see it in the list of roles on the Admin User->Role field.
I had to delete one other role in order to see it in the list.
Looks like the list is limited on displaying only 10 items while my available roles was 11.

![Screenshot 2024-11-13 110443](https://github.com/user-attachments/assets/78f81048-32e8-4273-8ba2-e0838b1bae69)

**Comment by givanz** [comment]
Hi

Thanks for the bug report, I fixed in the last update, changed file `/admin/controller/admin/user.php`

You can also quickly fix it by adding `limit => 100`

https://github.com/givanz/Vvveb/blob/master/admin/controller/admin/user.php#L36-L38

to 

```php
$options    =  [
	'type' => 'admin',
	'limit'=> 100 // <--- add this line
] + $this->global;
```

**Comment by m-bakoulis** [comment]
It works now, thank you!
