### ISSUE TITLE
Editor: Save button disappeared after updating files with the latest.zip

### ISSUE THREAD

**Issue by m-bakoulis** [givanz/Vvveb#229]
Hi I updated the files using the latest.zip (#226 ). 
After the Update I tried to edit my website and I the Save Button is missing so I am unable to apply changes.

![Screenshot 2024-11-21 112700](https://github.com/user-attachments/assets/4659beb6-05eb-4d0b-8102-f68bb590f4af)

Thanks in advance

**Comment by givanz** [comment]
Hi

This is caused by missing permission for save, do you have a rule such as `*/save` or  `editor/editor/save` in your deny list for the role?

Can you please share the deny/allow rules for the role?

**Comment by m-bakoulis** [comment]
Hi givaz,

yes sure.

![Screenshot 2024-11-26 154443](https://github.com/user-attachments/assets/fc95def0-5333-4f02-9cd8-6ab72d40b4fe)

![Screenshot 2024-11-26 154602](https://github.com/user-attachments/assets/bed04480-2868-4321-ac8f-cb56250a4057)

I didn't changed anything regarding this role, I just updated the files included in the latest.zip

Thanks in advance

**Comment by m-bakoulis** [comment]
I updated again with a newer release and the issue resolved. Thanks
