### ISSUE TITLE
Manage Roles: Delete and multiple delete/edit is not working

### ISSUE THREAD

**Issue by m-bakoulis** [givanz/Vvveb#230]
Hi I am trying to clean-up some tests I done, so I am trying to delete the unneeded Roles.
When I am trying to delete a single role or I use the multiple selection, nothing is happening.

![Screenshot 2024-11-21 113624](https://github.com/user-attachments/assets/ff2b5bd2-8daa-483f-8d01-6c580b18e094)

![Screenshot 2024-11-21 114347](https://github.com/user-attachments/assets/a56e844d-b81b-420c-b305-5d1b40c8c0e2)

Thanks in advance

**Comment by givanz** [comment]
Can you clear cache and see if it works? or you can manually delete cached templates from `/storage/compiled_templates`

**Comment by m-bakoulis** [comment]
I deleted the cache, but the issue remains. Also tried to delete the role that I wanted and still is not working.

**Comment by givanz** [comment]
After clearing cache the list still shows `Role name` for all rows or delete doesn't work? 

I'm unable to reproduce the bug from screenshot, it also works on demo https://demo.vvveb.com/admin/index.php?module=admin/roles

**Comment by m-bakoulis** [comment]
Seems like when I was transferring the updated files , 3 sql files and the roles.php failed to be transferred. 
I updated those files and now the issue resolved.
