### ISSUE TITLE
Admin users site access not working

### ISSUE THREAD

**Issue by fyr77** [givanz/Vvveb#240]
By default, an admin user can access all sites. When I try to change this and save the user, my setting is reset.

I also only have "All sites" available. 

![image](https://github.com/user-attachments/assets/65fd4235-2512-49d1-8f0a-835667241a5c)

Is this not implemented yet? Or is this a problem on my installation?

**Comment by givanz** [comment]
Thanks for the bug report, the sites list was empty on admin user page,  fixed file `/admin/controller/admin/user.php` https://github.com/givanz/Vvveb/commit/ea1c950ccf08a721489689cb3a4c3ce665e16798

If no individual sites are selected on save `all sites` will be selected by default, this is why the site access option is reset.

**Comment by fyr77** [comment]
Wonderful, thanks!
