### ISSUE TITLE
Fresh install missing WYSIWYG Content Editor

### ISSUE THREAD

**Issue by msvgeek** [givanz/Vvveb#241]
Starting with a fresh, standard install using the docker compose example in the documentation (https://docs.vvveb.com/docker-install), the WYSIWYG Content portion of any page flashes then disappears. It happens on multiple browsers as well. I also spun up a brand new container using just vvveb/vvvebcms:latest and a SQLite backends and the issue still happens. Inspecting the page HTML though, the WYSIWYG code is there - the field just doesn't show up.

![image](https://github.com/user-attachments/assets/6f9ae436-d427-47d8-a332-c777130cff7d)
![image](https://github.com/user-attachments/assets/9d254184-243c-45a4-82cc-bc9df384cfb5)
![image](https://github.com/user-attachments/assets/cc7cfe31-cc02-4b67-8448-bccce0953599)

**Comment by givanz** [comment]
Thanks for the bug report, I fixed it, `/public/js/libs/tinymce-dist/themes/` was missing in the last build.

**Comment by msvgeek** [comment]
Perfect! Thank you! A new docker pull brought down the update and it's showing properly now.
