### ISSUE TITLE
Error 500 on first login 

### ISSUE THREAD

**Issue by silicahd** [givanz/Vvveb#46]
Installation went well but I log in this is what i get. Any ideas? PHP 8.0 MySQL 5.7.40

![image](https://github.com/givanz/Vvveb/assets/7761519/5d8fdc88-f578-4056-90fb-0d10f357c93a)

![image](https://github.com/givanz/Vvveb/assets/7761519/e2b46f64-a05a-482b-afc3-7b1ef402ca8f)

**Comment by givanz** [comment]
Sorry, the error is caused by a query that tries to change mysql sql mode, I removed the query as it will not work with myql users that lack privileges and is not a good solution.

Please redownload the zip and update the files, no reinstallation is needed you will need to clear cache after update.

**Comment by silicahd** [comment]
Thank you. So I downloaded from the website again. Unzip and cleared the folder /storage/cache  did an F5 and same issue.

**Comment by givanz** [comment]
You will also need to clear `storage/model/admin` to regenerate the models from sql.

**Comment by silicahd** [comment]
You are the man. We will are looking to migrate all our customers projects to this CMS. A portion of each project we migrate to will be donated. Thank you for making this. Currently we are adding this to train our staff.
