### ISSUE TITLE
failed to open stream - error & fatal error if go admin panel

### ISSUE THREAD

**Issue by iffinland** [givanz/Vvveb#73]
![Screenshot 2024-01-27 21 13 47](https://github.com/givanz/Vvveb/assets/157421268/b9f2ec4b-bd64-41f3-91ca-f34c301eff6e)

I see this error if i go address http://myremoteVPSipaddress/admin/?module=settings/sites

VVVEB is installed on a VPS server running ubuntu

**Comment by givanz** [comment]
This happens because php does not have write permission for `storage` folder.

If this is a test site a quick fix is to run

```bash
sudo chmod  -R 0777 /var/www/html/storage
```
replacing the path with vvveb storage folder.

A better fix is to set the owner first and set stricter permissions

```bash
sudo chown -R www-data:www-data /var/www/html/storage
sudo chmod  -R 0755 /var/www/html/storage
```

**Comment by iffinland** [comment]
Thank you man, I hadn't used a personal web server in a long time and I had forgotten such a basic thing. I'm sorry for wasting your time
