### ISSUE TITLE
Error after try 'save as reusable'

### ISSUE THREAD

**Issue by lilianzzz** [givanz/Vvveb#78]
Error after try 'save as reusable'
If additional information is required, I am ready to provide

```
Warning: file_put_contents(/home/d/dissokdf/techdeer.ru/public_html/public/themes/blink-coming-soon/blocks/reusable/header.html): Failed to open stream: No such file or directory in /home/d/dissokdf/techdeer.ru/public_html/admin/controller/editor/editor.php on line 327 {"success":false,"message":"Error saving!"}
```

**Comment by givanz** [comment]
Thanks for the bug report.

This theme does not come with default blocks and the folder for blocks is missing.

Can you please replace https://github.com/givanz/Vvveb/blob/master/admin/controller/editor/editor.php#L325

```php
@mkdir($folder);
````

with 

```php
@mkdir($folder, 0755 & ~umask(), true);
```

If it still fails to create the folders try to create the `blocks/reusable` folders inside `/public/themes/blink-coming-soon/` manually and set write permission.

**Comment by lilianzzz** [comment]
![image](https://github.com/givanz/Vvveb/assets/24529543/a5044188-9afb-4e36-93b8-df670b39c05d)

```@mkdir($folder, 0755 & ~umask(), true);``` 

It helped, the files are being created. but in the editor after refreshing the page they disappear
![image](https://github.com/givanz/Vvveb/assets/24529543/eb8eb25b-10fb-4d7a-884e-fc1281742e40)

**Comment by givanz** [comment]
Thanks for feedback, to fix this issue please redownload latest.zip and update the files on the server.

Changed files under /admin/controller/editor and /system but update all files if possible.

You need to save a new block/section to regenerate the list.

**Comment by lilianzzz** [comment]
It seems that the project was transferred correctly - 
I left only the database and 
config/sites.php (it also changed slightly) and 
the theme from public/themes/blink-coming-soon (with cleared block/section)

but the error persists - it still does not display blocks when updating. However, it no longer saves the file to the /public/themes/blink-coming-soon/blocks/reusable directory

![image](https://github.com/givanz/Vvveb/assets/24529543/25b68daa-2c50-4e77-9e18-4a5675f4fc35)

**Comment by givanz** [comment]
Sorry this is caused by a small change that I made and didn't test.

Please change in `admin/controller/editor/reusable.php` line 58 

```php
return DIR_THEMES . DS . $this->request->get['theme'] ?? Sites::getTheme() ?? 'default';
```

with

```php
return DIR_THEMES . DS . ($this->request->get['theme'] ?? Sites::getTheme() ?? 'default');
```

I also updated the file in latest.zip.

No database change is needed, you can skip `/config` folder when updating to keep site settings like selected theme.

**Comment by lilianzzz** [comment]
Great! everything works now =) Thanks
