### ISSUE TITLE
CSS is reset with fill and borders when the font is changed

### ISSUE THREAD

**Issue by lilianzzz** [givanz/Vvveb#80]
CSS is reset with fill and borders when the font is changed.

If you need additional information, please write =)

https://github.com/givanz/Vvveb/assets/24529543/64692389-e96d-441d-9bd8-30d92e7a32de

**Comment by givanz** [comment]
Thanks for the detailed video, I managed to reproduce and fix the bug.

Please redownload latest.zip and update `public/js` folder and clear browser cache.

**Comment by lilianzzz** [comment]
Great, the css is not reset, although now the font size and other parameters from the side menu do not change =)

![vivaldi_fO00v8zPCz](https://github.com/givanz/Vvveb/assets/24529543/9121c56d-5015-4ad7-9804-99ed2a4a4cc5)

**Comment by givanz** [comment]
Thanks for the bug report.

I just checked the heading and the font size was set with the inline text editor, the one that shows on double click on text.

The inline text editor sets the properties with inline `style` on the element this has higher precedence overriding any change made from the panel that sets the property in css.

I will make some tests and see how to change the text editor to also save to css to avoid this issue.

You can use the text editor to change the font size until it's fixed.

**Comment by lilianzzz** [comment]
Apparently the IDs were broken, after changing the ID for the title the problem disappeared. It’s true that you have to manually enter at least something into the ID for all elements to  “unstick”
![image](https://github.com/givanz/Vvveb/assets/24529543/2dbbe8da-51c3-4af4-9ec9-b9d729314f2f)

**Comment by givanz** [comment]
Fixed it, please update `/public/js/vvvebjs/builder.js` from latest.zip and clear cache.

For elements that don't have unique identifiers the css selector is generated from parent elements and it applies to all similar child elements.

Sometimes this can be useful for example if you want to change the color for all icons in the same list/section etc 

When this it's not wanted it can be solved be setting a unique id.

**Comment by lilianzzz** [comment]
Thank you very much =). am I closing the issue?

**Comment by givanz** [comment]
With welcome, you can close it if it's fixed.
