### ISSUE TITLE
Currency rates are US Centric

### ISSUE THREAD

**Issue by Twilight-Computer** [givanz/Vvveb#99]
Currency appears to be US Centric.  Something for eCommerce go live;

If the default Country is changed to something else (eg Australia), then that Country should assume a currency rate of "1" and all others relative to that value.

**Comment by givanz** [comment]
Sample data has USD rate as 1 and set as default currency.

Default currency can be set per site from `settings > site > local` you will need to clear browser cookies after the change as the default currency is set per session on first visit.

The default currency (with rate 1) is global and is used for products base price for all sites.

Changing rates automatically when changing site default country might not be desired on some setups.

The included `Currency Update` plugin is under development and will provide automatic currency rate synchronization from ECB.
